export interface ITrip {
  id: number,
  authorId: number,
  authorUsername: string,
  authorAge: number,
  authorGender: string,
  budget: number,
  summary: string,
  description: string,
  from: Date,
  to: Date,
  images: string,
  maxPassengers: number,
  countries: string[],
  ativities: string[],
  places: string[],
  passengers: number[],
}
