name: deploy to heroku

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  log-in-and-deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_APP_KEY }}
        run: heroku container:login
      
      - name: build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_APP_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      
      - name: build and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_APP_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
